### PR TITLE
Gradle plugin for RAML JAX-RS code generation

### PR DESCRIPTION
**Pull request by jdpgrailsdev**
This pull request contains a Gradle plugin for RAML JAX-RS code generation.  It is modeled after the Maven plugin in terms of configuration options and logic.  The included README contains information on usage and configuration.  I have also added Gradle build scripts to the Jersey sample application, which can be used to test the plugin.  The plugin itself still needs to have a Gradle task added to support the publishing of the built artifact to a remote Maven repository.  To try this all out:
- `cd gradle-plugin`
- `./gradlew build install`
- `cd ../jersey-example`
- `./gradlew raml-generate`

It is also worth noting that there is an issue with the Gradle License plugin, so its currently set to non-strict mode and there is a comment in the `build.gradle` file of the RAML plugin.

### CODE REVIEW

**Comment by JohnBaileyNike** [comment]
What is the status on getting this merged?

**Comment by jdpgrailsdev** [comment]
@JohnBaileyN I haven't heard a word from the maintainers of the repo as to the status.  The branch most likely needs updating, as I created the plugin over a year ago.

**Comment by petrochenko-pavel-a** [comment]
Actually it is merged. But not tested really well. So any issues are very
appreciated.

Regards,
Pavel

**Comment by JohnBaileyN** [comment]
@petrochenko-pavel-a  I do not see this as being merged, both in terms of the status of this Pull Request (Open) and in that the directories in the _master_ do not contain the changes.

**Comment by petrochenko-pavel-a** [comment]
Ah, this is because project now lives at
https://github.com/mulesoft/raml-for-jax-rs/ please see
https://github.com/mulesoft/raml-for-jax-rs/tree/master/raml-to-jaxrs/gradle-plugin.
And thanks again for this contribution.

Regards,
Pavel

**Comment by jdpgrailsdev** [comment]
@petrochenko-pavel-a Sounds like I should close this PR then, so that it will stop the confusion.

**Comment by petrochenko-pavel-a** [comment]
Yep, thanks a lot

**Pull request closed without merging**
